### ISSUE TITLE
Getting `Operation Not Permitted` errors on 'cfjump'

### ISSUE THREAD

**Issue by akoranne** [RamXX/cfjump#3]
Hi,

I pulled the latest docker image and added `cfj` in my '/usr/local/bin'. This is on my Mac.
When I connect to the docker image, I get 'operation not permitted' error.

Here is the log..
```
 $> cfj all
Installing CF plugins
chown: changing ownership of '/home/ops/.bashrc': Operation not permitted
chown: changing ownership of '/home/ops/.firstrun': Operation not permitted
chown: changing ownership of '/home/ops/.touchfile': Operation not permitted
chown: changing ownership of '/home/ops': Operation not permitted
FAILED
Config error: mkdir /home/ops/.cf: permission denied
all $
all $
all $ touch abc
touch: cannot touch 'abc': Permission denied
all $ sudo su -
root@4a764204c1ee:~# ls -l
total 0
-rw-r--r-- 1 ops ops 0 Apr 27 11:55 immutable
root@4a764204c1ee:~# pwd
/root
root@4a764204c1ee:~# cd /home/ops
root@4a764204c1ee:/home/ops# cd ..
root@4a764204c1ee:/home# ls -l
total 0
drwxr-xr-x 5 root root 170 Apr 26 20:48 ops
root@4a764204c1ee:/home# chmod +w ops
chmod: changing permissions of 'ops': Operation not permitted
root@4a764204c1ee:/home#
```

Can you please let me know, how I can fix it?

**Comment by RamXX** [comment]
@akoranne I replicated the error and I'm looking into it. It seems to occur only on MacOS. Cfjump was all done and developed on Linux. I had never ran it on a Mac until now, so let me find out what's unique about this...

As a workaround, I'd recommend to run this on a Linux VM on your Mac via Fusion or Virtualbox for the moment. I'll put a note in the README about this until I can figure it out. I've been asking several smart folks today on this and everybody seems to be scratching their heads.

**Comment by RamXX** [comment]
OK, so it seems this issue is [well documented for Mac](https://forums.docker.com/t/chmod-permission-denied/9360), so I now force a 777 on the newly created directory as a workaround in OS X and it seems to work fine, with both, the standard and edge variants of Docker. @akoranne please make sure you use the new `cfj` CLI and delete the directory of the failed jumpboxes. Don't hesitate to reopen this if you see anything different.
